foreground = no
pid = /run/stunnel4.pid

[koshibar-ssh]
accept = 0.0.0.0:443
connect = 127.0.0.1:8080

cert = /Koshibar/100%/tls/stunnel.pem

sslVersionMin = TLSv1.2

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
